# Generated by Django 5.1.1 on 2025-08-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('coefficient', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
