# Generated by Django 5.1.1 on 2025-08-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousecoefficient',
            name='date',
            field=models.DateTimeField(default='2025-01-01T00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehousecoefficient',
            name='coefficient',
            field=models.IntegerField(),
        ),
    ]
