# Generated by Django 5.1.1 on 2025-08-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_warehousecoefficient_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehousecoefficient',
            unique_together={('office_id', 'date')},
        ),
    ]
