# Generated by Django 5.1.1 on 2025-10-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotifiedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.BigIntegerField()),
                ('date_iso', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['warehouse_id', 'date_iso'], name='wb_coeff_st_warehou_6db7a4_idx')],
                'unique_together': {('warehouse_id', 'date_iso')},
            },
        ),
    ]
