# Generated by Django 5.1.1 on 2025-10-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_coeff_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NotifiedSlot',
        ),
        migrations.AddIndex(
            model_name='tgsubscriber',
            index=models.Index(fields=['chat_id', 'active'], name='wb_coeff_st_chat_id_b2ffb5_idx'),
        ),
    ]
