# Generated by Django 5.1.1 on 2025-10-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_history_view', '0002_pricerecord_article_pricerecord_partner_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricerecord',
            options={'ordering': ['-created_at', 'partner_id', 'item_id']},
        ),
        migrations.RemoveConstraint(
            model_name='pricerecord',
            name='uniq_snapshot_partner_dest_item',
        ),
        migrations.RemoveIndex(
            model_name='pricerecord',
            name='API_ShowPri_created_a3d461_idx',
        ),
        migrations.RemoveField(
            model_name='pricerecord',
            name='dest',
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='article',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='partner_name',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='price_before_spp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['created_at', 'partner_id'], name='API_ShowPri_created_ab14d0_idx'),
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['partner_name'], name='API_ShowPri_partner_9e0bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['article'], name='API_ShowPri_article_d46d11_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.UniqueConstraint(fields=('created_at', 'partner_id', 'item_id'), name='uniq_snapshot_partner_item'),
        ),
    ]
