# Generated by Django 5.1.1 on 2025-10-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_history_view', '0003_alter_pricerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricerecord',
            options={'ordering': ['-created_at', 'partner_id', 'dest', 'item_id']},
        ),
        migrations.RemoveConstraint(
            model_name='pricerecord',
            name='uniq_snapshot_partner_item',
        ),
        migrations.RemoveIndex(
            model_name='pricerecord',
            name='API_ShowPri_created_ab14d0_idx',
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='dest',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['created_at', 'partner_id', 'dest'], name='API_ShowPri_created_a3d461_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricerecord',
            constraint=models.UniqueConstraint(fields=('created_at', 'partner_id', 'dest', 'item_id'), name='uniq_snapshot_partner_dest_item'),
        ),
    ]
