# Generated by Django 5.1.1 on 2025-09-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('partner_id', models.BigIntegerField(db_index=True)),
                ('dest', models.CharField(db_index=True, max_length=32)),
                ('item_id', models.BigIntegerField(db_index=True)),
                ('item_name', models.CharField(max_length=255)),
                ('price_basic', models.IntegerField()),
                ('price_product', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at', 'partner_id', 'dest', 'item_id'],
                'indexes': [models.Index(fields=['created_at', 'partner_id', 'dest'], name='API_ShowPri_created_a3d461_idx'), models.Index(fields=['item_id'], name='API_ShowPri_item_id_388b3b_idx')],
                'constraints': [models.UniqueConstraint(fields=('created_at', 'partner_id', 'dest', 'item_id'), name='uniq_snapshot_partner_dest_item')],
            },
        ),
    ]
