"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ch18xz5-r09btu@yvc@)#)ryf@!afiao*yw)w#83&g5!x=u#lg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = ["guzhva.online", "www.guzhva.online"]
if DEBUG:
    ALLOWED_HOSTS += ["127.0.0.1", "localhost", "[::1]"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    "get_price",
    "django_apscheduler",
    'hucster_change',
    'ozon_parser',
    "price_history_view.apps.PriceHistoryViewConfig",
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Рекомендуется иметь валидный таймзон
TIME_ZONE = 'Europe/Moscow'   # или ваша


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CRONJOBS = [
    ('*/5 * * * *', 'django.core.management.call_command', ['fetch_prices']),
]

# Чтобы планировщик автозапускался (можете выключить в проде, если нужно)
APSCHEDULER_AUTOSTART = True

# Не обязательно, но удобно для логов
APSCHEDULER_DATETIME_FORMAT = "Y-m-d H:i:s"

load_dotenv(BASE_DIR / '.env')

# Можно поддержать несколько ключей, через запятую:
HUCSTER_API_KEYS = [x.strip() for x in os.getenv('HUCSTER_API_KEYS', '').split(',') if x.strip()]

# Базовый URL каталога для сборки ссылок из ключа:
HUCSTER_BASE_URL = os.getenv('HUCSTER_BASE_URL', 'https://market.e-teleport.ru/catalog/')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

STATIC_ROOT = '/opt/django-app/django-api/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # если хранишь статику рядом с кодом
# для продакшена:


WB_DISCOUNTS_API_TOKEN = os.getenv("WB_API_TOKEN", "")  # токен «Скидки и цены»
WB_SHOP_ID = int(os.getenv("WB_SHOP_ID", "215484"))               # наш кабинет JKeratin
WB_DISCOUNTS_API_URL = "https://discounts-prices-api.wildberries.ru/api/v2/list/goods/filter"